### Request /login API => Success
POST {{baseUrl}}/system/auth/login
Content-Type: application/json
tenant-id: {{adminTenantId}}
tag: iBonding.local

{
  "username": "admin",
  "password": "admin123",
  "uuid": "3acd87a09a4f48fb9118333780e94883",
  "code": "1024"
}

### Request /login API => Success (No Verification Code)
POST {{baseUrl}}/system/auth/login
Content-Type: application/json
tenant-id: {{adminTenantId}}

{
  "username": "admin",
  "password": "admin123"
}

### Request /get-permission-info API => Success
GET {{baseUrl}}/system/auth/get-permission-info
Authorization: Bearer {{token}}
tenant-id: {{adminTenantId}}

### Request /list-menus API => Success
GET {{baseUrl}}/system/list-menus
Authorization: Bearer {{token}}
#Authorization: Bearer a6aa7714a2e44c95aaa8a2c5adc2a67a
tenant-id: {{adminTenantId}}
