### Send Message (Segmented)
POST {{baseUrl}}/ai/chat/message/send
Content-Type: application/json
Authorization: {{token}}
tenant-id: {{adminTenantId}}

{
  "conversationId": "1781604279872581724",
  "content": "你是 OpenAI 么？"
}

### Send Message (Streaming)
POST {{baseUrl}}/ai/chat/message/send-stream
Content-Type: application/json
Authorization: {{token}}
tenant-id: {{adminTenantId}}

{
  "conversationId": "1781604279872581724",
  "content": "1+1=?"
}

### Get the Message List of the Specified Conversation
GET {{baseUrl}}/ai/chat/message/list-by-conversation-id?conversationId=1781604279872581649
Authorization: {{token}}

### Delete Message
DELETE {{baseUrl}}/ai/chat/message/delete?id=50
Authorization: {{token}}