### Request /create API => Success
POST {{appApi}}//member/address/create
Content-Type: application/json
tenant-id: {{appTenantId}}
Authorization: Bearer {{appToken}}

{
  "name": "ibonding",
  "mobile": "15601691300",
  "areaId": "610632",
  "postCode": "200000",
  "detailAddress": "Agaru 233 号 666 室",
  "defaulted": true
}

### Request /update API => Success
PUT {{appApi}}//member/address/update
Content-Type: application/json
tenant-id: {{appTenantId}}
Authorization: Bearer {{appToken}}

{
  "id": "1",
  "name": "ibonding888",
  "mobile": "15601691300",
  "areaId": "610632",
  "postCode": "200000",
  "detailAddress": "Agaru 233 号 666 室",
  "defaulted": false
}

### Request /delete API => Success
DELETE {{appApi}}//member/address/delete?id=2
Content-Type: application/json
tenant-id: {{appTenantId}}
Authorization: Bearer {{appToken}}

### Request /get API => Success
GET {{appApi}}//member/address/get?id=1
Content-Type: application/json
tenant-id: {{appTenantId}}
Authorization: Bearer {{appToken}}

### Request /get-default API => Success
GET {{appApi}}//member/address/get-default
Content-Type: application/json
tenant-id: {{appTenantId}}
Authorization: Bearer {{appToken}}

### Request /list API => Success
GET {{appApi}}//member/address/list
Content-Type: application/json
tenant-id: {{appTenantId}}
Authorization: Bearer {{appToken}}
