### /pay/create Submit Payment Order【alipay_pc】
POST {{appApi}}/pay/order/submit
Content-Type: application/json
Authorization: Bearer {{appToken}}
tenant-id: {{appTenantId}}

{
  "id": 174,
  "channelCode": "alipay_pc"
}

### /pay/create Submit Payment Order【wx_bar】
POST {{appApi}}/pay/order/submit
Content-Type: application/json
Authorization: Bearer {{appToken}}
tenant-id: {{appTenantId}}

{
  "id": 202,
  "channelCode": "wx_bar",
  "channelExtras": {
    "authCode": "134042110834344848"
  }
}

### /pay/create Submit Payment Order【wx_pub】
POST {{appApi}}/pay/order/submit
Content-Type: application/json
Authorization: Bearer {{appToken}}
tenant-id: {{appTenantId}}

{
  "id": 202,
  "channelCode": "wx_pub",
  "channelExtras": {
    "openid": "ockUAwIZ-0OeMZl9ogcZ4ILrGba0"
  }
}

### /pay/create Submit Payment Order【wx_lite】
POST {{appApi}}/pay/order/submit
Content-Type: application/json
Authorization: Bearer {{appToken}}
tenant-id: {{appTenantId}}

{
  "id": 202,
  "channelCode": "wx_lite",
  "channelExtras": {
    "openid": "oLefc4g5GjKWHJjLjMSXB3wX0fD0"
  }
}

### /pay/create Submit Payment Order【wx_native】
POST {{appApi}}/pay/order/submit
Content-Type: application/json
Authorization: Bearer {{appToken}}
tenant-id: {{appTenantId}}

{
  "id": 202,
  "channelCode": "wx_native"
}
